version: '3.9'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile  
    ports:
      - "8080:8080"
    environment:
      - PORT=8080
      - DATABASE_CONNECTION_STRING=server=host.docker.internal;port=3306;database=Baza_danych_testowa;user=root;password=Maba@@22
